# name: CI

# on: push

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: ./.github/actions/setup-node
#       - run: pnpm build
#       - uses: actions/upload-pages-artifact@v3
#         with:
#           path: dist
#   deploy:
#     needs: build
#     permissions:
#       pages: write
#       id-token: write
#     environment:
#       name: github-pages
# url: ${{ steps.deployment.outputs.page_url }}
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/deploy-pages@v4
#         id: deployment
name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node

      - name: Build auto version
        run: pnpm run build:auto
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Build bioluminescence version
        run: |
          pnpm run build:bioluminescence
          mv dist dist_bioluminescence

      - name: Upload bioluminescence version
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist_bioluminescence
          name: bioluminescence
      - run: ls -la dist_bioluminescence

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy root version
        uses: actions/deploy-pages@v4
        id: deployment
        with:
          artifact_name: github-pages
      - name: Deploy bioluminescence version
        uses: actions/deploy-pages@v4
        id: deployment-bioluminescence
        with:
          artifact_name: bioluminescence
